config/routes.rb
Rails.application.routes.draw do
  resources :stories
  devise_for :users

  get 'home/index'
  get 'home/about'
  get 'home/howitworks'

  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
# Configuración para que Devise acepte más parámetros
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
# No pasamos :admin por ahora, dado que se cambiará por consola solamente.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :remember_me, :admin, :media, :name, :city, :country, :startdate, :nationality, :currentjob, :description])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :remember_me, :admin, :media, :name, :city, :country, :startdate, :nationality, :currentjob, :description])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def howitworks
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:from, :for, :type, :price, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/about.html.erb
  <div class="row justify-content-center">
    <div class="col-8">
      <h1>Sobre nosotros</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pellentesque ante tristique, commodo ex vitae, lacinia nisi. Donec nec nisl interdum dolor facilisis volutpat ut non sapien. Ut mattis semper ligula, sit amet laoreet odio scelerisque a. Morbi erat eros, lacinia vitae mattis nec, dapibus eu mi. Donec porta lacinia arcu, ac dictum nisl. Donec lorem dui, sollicitudin sed vestibulum in, laoreet laoreet nisl. Morbi luctus pretium felis, pretium elementum libero blandit ut. Donec lacinia, quam non pellentesque accumsan, nisi arcu pharetra dolor, eu semper magna tellus nec lectus. Quisque a pellentesque ipsum, in rhoncus tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi volutpat vitae ante a convallis. Nunc ultricies nunc feugiat, rhoncus mauris at, cursus turpis. Donec sed sem urna. Quisque augue risus, fringilla vel purus a, varius semper orci.</p>

      <p>Praesent purus sem, sodales ut rhoncus sed, varius ac libero. Maecenas suscipit, sapien at sodales cursus, eros eros sagittis diam, vitae efficitur turpis felis nec ex. In ultrices commodo mauris, a bibendum nisl dignissim sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla mattis mauris vel erat ultricies finibus. Sed vitae magna metus. Suspendisse potenti. Phasellus lobortis laoreet purus. Nulla lorem mi, elementum quis feugiat sit amet, vestibulum eu quam. Quisque eu ornare libero. Donec sagittis feugiat sem nec sagittis. Nunc imperdiet bibendum massa, sed blandit urna suscipit vitae. Morbi nec sagittis nulla.</p>

      <p>In lorem nisi, viverra id rhoncus a, semper nec libero. Mauris congue metus vel interdum pellentesque. Nullam justo eros, fermentum vel congue non, placerat sit amet sem. Ut eget ligula ac ante accumsan vehicula. Nulla consectetur elementum augue, eu sollicitudin tellus pharetra in. Curabitur vulputate enim et varius placerat. Integer faucibus faucibus nisl in hendrerit. Phasellus in varius eros, efficitur convallis ex. Morbi vulputate enim in ante vehicula venenatis. Pellentesque vulputate, elit at placerat pellentesque, nulla ligula pharetra felis, vitae lobortis eros velit ac nulla. Cras justo urna, egestas laoreet sagittis id, semper et erat. Vestibulum eleifend augue vitae ligula consequat tempor. Nulla non nibh vel neque maximus pharetra.</p>
    </div>
  </div>
  <div class="row justify-content-around">
    <div class="col-md-8">

    </div>
  </div>

app/views/home/howitworks.html.erb
  <div class="row justify-content-center">
    <div class="col-8">
      <h1>¿Cómo funciona?</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pellentesque ante tristique, commodo ex vitae, lacinia nisi. Donec nec nisl interdum dolor facilisis volutpat ut non sapien. Ut mattis semper ligula, sit amet laoreet odio scelerisque a. Morbi erat eros, lacinia vitae mattis nec, dapibus eu mi. Donec porta lacinia arcu, ac dictum nisl. Donec lorem dui, sollicitudin sed vestibulum in, laoreet laoreet nisl. Morbi luctus pretium felis, pretium elementum libero blandit ut. Donec lacinia, quam non pellentesque accumsan, nisi arcu pharetra dolor, eu semper magna tellus nec lectus. Quisque a pellentesque ipsum, in rhoncus tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi volutpat vitae ante a convallis. Nunc ultricies nunc feugiat, rhoncus mauris at, cursus turpis. Donec sed sem urna. Quisque augue risus, fringilla vel purus a, varius semper orci.</p>

      <p>Praesent purus sem, sodales ut rhoncus sed, varius ac libero. Maecenas suscipit, sapien at sodales cursus, eros eros sagittis diam, vitae efficitur turpis felis nec ex. In ultrices commodo mauris, a bibendum nisl dignissim sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla mattis mauris vel erat ultricies finibus. Sed vitae magna metus. Suspendisse potenti. Phasellus lobortis laoreet purus. Nulla lorem mi, elementum quis feugiat sit amet, vestibulum eu quam. Quisque eu ornare libero. Donec sagittis feugiat sem nec sagittis. Nunc imperdiet bibendum massa, sed blandit urna suscipit vitae. Morbi nec sagittis nulla.</p>

      <p>In lorem nisi, viverra id rhoncus a, semper nec libero. Mauris congue metus vel interdum pellentesque. Nullam justo eros, fermentum vel congue non, placerat sit amet sem. Ut eget ligula ac ante accumsan vehicula. Nulla consectetur elementum augue, eu sollicitudin tellus pharetra in. Curabitur vulputate enim et varius placerat. Integer faucibus faucibus nisl in hendrerit. Phasellus in varius eros, efficitur convallis ex. Morbi vulputate enim in ante vehicula venenatis. Pellentesque vulputate, elit at placerat pellentesque, nulla ligula pharetra felis, vitae lobortis eros velit ac nulla. Cras justo urna, egestas laoreet sagittis id, semper et erat. Vestibulum eleifend augue vitae ligula consequat tempor. Nulla non nibh vel neque maximus pharetra.</p>
    </div>
  </div>

app/views/home/index.html.erb
  <div class="row justify-content-center">
    <div class="col-8">
      <h1>💼 Portable Journalism</h1>
      <p>La red internacional de periodistas nómadas alrededor del mundo</p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= link_to 'Inscríbete', new_user_registration_path, class: "btn btn-lg btn-block btn-outline-info", role: "button" %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>[local] 💼 Portable Journalism</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %> <%# NO BORRAR JAMÁS %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col">
          <nav class="navbar navbar-expand-md navbar-light bg-faded">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarPJ" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarPJ">
              <div class="navbar-nav">
                <%= link_to 'Portada', root_path, class: "nav-item nav-link" %>
                <%= link_to 'Quiénes somos', home_about_path, class: "nav-item nav-link" %>
                <%= link_to '¿Cómo funciona?', home_howitworks_path, class: "nav-item nav-link" %>
                <% if user_signed_in? %>
                  <%= link_to 'Editar perfil', edit_user_registration_path, class: "btn btn-outline-warning", role: "button" %>
                  <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger", role: "button" %>
                <% else %>
                <%= link_to 'Ingresa', new_user_session_path, class: "btn btn-outline-success", role: "button" %>
                <% end %>
              </div>
            </div>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <span class="notice"><%= notice %></span>
          <span class="alert"><%= alert %></span>
        </div>
      </div>
      <div class="row">
        <div class="col" style="min-height: 60vh;">
          <%= yield %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="bg-faded">
            <div class="row">
              <div class="col">
                Espacio para footer.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_field :from, id: :story_from %>
  </div>

  <div class="field">
    <%= form.label :for %>
    <%= form.text_field :for, id: :story_for %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :story_type %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :story_price %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :story_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :story_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>For</th>
      <th>Type</th>
      <th>Price</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.from %></td>
        <td><%= story.for %></td>
        <td><%= story.type %></td>
        <td><%= story.price %></td>
        <td><%= story.title %></td>
        <td><%= story.description %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @story.from %>
</p>

<p>
  <strong>For:</strong>
  <%= @story.for %>
</p>

<p>
  <strong>Type:</strong>
  <%= @story.type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @story.price %>
</p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>